import * as THREE from 'three';
let GL = GLSL.V300ES.Type;
export const TYPES: Record<GLSL.V300ES.Type, [string, any]> = {
    [GL.Bool]: ['boolean', false],
    [GL.Int]: ['number', 0],
    [GL.Uint]: ['number', 0],
    [GL.Float]: ['number', 0],
    [GL.Vec2]: ['THREE.Vector2', new THREE.Vector2()],
    [GL.Vec3]: ['THREE.Vector3', new THREE.Vector3()],
    [GL.Vec4]: ['THREE.Vector4', new THREE.Vector4()],
    [GL.Bvec2]: ['THREE.Vector2', new THREE.Vector2()],
    [GL.Bvec3]: ['THREE.Vector3', new THREE.Vector3()],
    [GL.Bvec4]: ['THREE.Vector4', new THREE.Vector4()],
    [GL.Ivec2]: ['THREE.Vector2', new THREE.Vector2()],
    [GL.Ivec3]: ['THREE.Vector3', new THREE.Vector3()],
    [GL.Ivec4]: ['THREE.Vector4', new THREE.Vector4()],
    [GL.Uvec2]: ['THREE.Vector2', new THREE.Vector2()],
    [GL.Uvec3]: ['THREE.Vector3', new THREE.Vector3()],
    [GL.Uvec4]: ['THREE.Vector4', new THREE.Vector4()],
    [GL.Mat2]: ['THREE.Matrix2', new THREE.Matrix2()],
    [GL.Mat3]: ['THREE.Matrix3', new THREE.Matrix3()],
    [GL.Mat4]: ['THREE.Matrix4', new THREE.Matrix4()],
    [GL.Mat2x2]: ['THREE.Matrix2', new THREE.Matrix2()],
    [GL.Mat2x3]: ['[number, number, number, number, number, number]', [1, 0, 0, 1, 0, 0]],
    [GL.Mat2x4]: ['[number, number, number, number, number, number, number, number]', [1, 0, 0, 1, 0, 0, 0, 0]],
    [GL.Mat3x2]: ['[number, number, number, number, number, number]', [1, 0, 0, 1, 0, 0]],
    [GL.Mat3x3]: ['THREE.Matrix3', new THREE.Matrix3()],
    [GL.Mat3x4]: ['[number, number, number, number, number, number, number, number, number, number, number, number]', [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]],
    [GL.Mat4x2]: ['[number, number, number, number, number, number, number, number]', [1, 0, 0, 1, 0, 0, 0, 0]],
    [GL.Mat4x3]: ['[number, number, number, number, number, number, number, number, number, number, number, number]', [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]],
    [GL.Mat4x4]: ['THREE.Matrix4', new THREE.Matrix4()],    
    [GL.Sampler2D]: ['THREE.Texture', new THREE.Texture()],
    [GL.Sampler3D]: ['THREE.Texture', new THREE.Texture()],
    [GL.SamplerCube]: ['THREE.Texture', new THREE.Texture()],
    [GL.SamplerCubeShadow]: ['THREE.Texture', new THREE.Texture()],
    [GL.Sampler2DShadow]: ['THREE.Texture', new THREE.Texture()],
    [GL.Sampler2DArray]: ['THREE.Texture', new THREE.Texture()],
    [GL.Sampler2DArrayShadow]: ['THREE.Texture', new THREE.Texture()],
    [GL.Isampler2D]: ['THREE.Texture', new THREE.Texture()],
    [GL.Isampler3D]: ['THREE.Texture', new THREE.Texture()],
    [GL.IsamplerCube]: ['THREE.Texture', new THREE.Texture()],
    [GL.Isampler2DArray]: ['THREE.Texture', new THREE.Texture()],
    [GL.Usampler2D]: ['THREE.Texture', new THREE.Texture()],
    [GL.Usampler3D]: ['THREE.Texture', new THREE.Texture()],
    [GL.UsamplerCube]: ['THREE.Texture', new THREE.Texture()],
    [GL.Usampler2DArray]: ['THREE.Texture', new THREE.Texture()],
};
